MyportFolio1/Areas/Admin/Controllers/RasemeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyportFolio1.BL;
using MyportFolio1.Models;

namespace MyportFolio1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RasemeController : Controller
    {
        IIraseme ixresa;
        public RasemeController(IIraseme ixxc)
        {
            ixresa = ixxc;
        }
        public IActionResult MyRaseme()
        {
            return View(ixresa.getall());
        }
        public IActionResult Edite(int? Id)
        {
            if (Id != null)
            {
                return View(ixresa.getbyid(Convert.ToInt32(Id)));
            }
            else
            {
                return View();
            }
          

        }
        public IActionResult Save(Tbresme vrase)
        {
            if (ModelState.IsValid)
            {
                if(vrase.Id==0|| vrase.Id == null)
                {
                    ixresa.Add(vrase);
                    return RedirectToAction("MyRaseme");
                }
                else
                {
                    ixresa.Edite(vrase);
                    return RedirectToAction("MyRaseme");
                }
               
            }
            else
            {
                return View(vrase);
            }
         
        }
        public IActionResult Delete(int Id)
        {

            ixresa.Delete(Id);
            return RedirectToAction("MyRaseme");
        }
    }
}

MyportFolio1/Areas/Admin/Views/Raseme/MyRaseme.cshtml
@model List<MyportFolio1.Models.Tbresme>

<!-- Datatable CSS -->
<link rel="stylesheet" href="~/Admin/css/dataTables.bootstrap4.min.css">

<!-- Main Wrapper -->
<div class="main-wrapper">


    <div class="page-wrapper">
        <div class="content container-fluid">

            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Data Tables</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Data Tables</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="card mb-0">
                        <div class="card-header">
                            <h4 class="card-title mb-0"><a asp-controller="Raseme" asp-action="Edite" class="btn btn-success">Add New Data</a></h4>
                            <p class="card-text">
                                This is the most basic example of the datatables with zero configuration. Use the <code>.datatable</code> class to initialize datatables.
                            </p>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="datatable table table-stripped mb-0">
                                    <thead>
                                        <tr>


                                            <th>Titel</th>
                                            <th>Experins</th>
                                            <th>Discrption</th>
                                            <th>Skaills</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var irase in Model)
                                        {
                                        <tr>
                                            <td>@irase.Title</td>
                                            <td>@irase.Exp</td>
                                            <td>@irase.Dis</td>
                                            <td>@irase.Skills</td>

                                            <td>
                                                <a asp-controller="Raseme" asp-action="Edite" asp-route-Id="@irase.Id" class="btn btn-info"> modfai</a>
                                                <a asp-controller="Raseme" asp-action="Delete" asp-route-Id="@irase.Id" class="btn btn-danger"> Delete</a>
                                            </td>
                                        </tr>

                                        }



                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- /Page Wrapper -->

</div>
@section scripts
{
    <!-- Datatable JS -->
    <script src="~/Admin/js/jquery.dataTables.min.js"></script>
    <script src="~/Admin/js/dataTables.bootstrap4.min.js"></script>
}

<!-- Datatable JS -->
<script src="~/Admin/js/jquery.dataTables.min.js"></script>
<script src="~/Admin/js/dataTables.bootstrap4.min.js"></script>